### ISSUE TITLE
Failed Classifier Test

### ISSUE THREAD

**Issue by beaubarbour** [salestock/fastText.py#49]
We are trying to use fastText.py for text classification but we can't even get a pulse out of it. we were able to get the skipgram stuff to work, so the installation appears sound. The problem occurs with a simple test where data.train.txt contains the following training data, but the python script hangs with no result. We're not looking for anything from this test except confirmation that it's running. Could it be hanging because a lack of training data? or are there parameters that we should be setting to make it work?

Training Data: 

__label__food , beau likes icecream 
__label__tech , amy likes bikes 
__label__food , fred likes burritos 
__label__tech , mike likes computers 
__label__tech , apple just sold another 1000 iphones 
__label__food , john hates tacos 
__label__tech , john loves computers 
__label__tech , sarah is the only one using the internet 
__label__food , sarah is the only one using the kitchen for dinner 
__label__tech , when john is in his car he listens to the radio 

here's where we in pass it to fastText:

import fasttext
classifier = fasttext.supervised('data.train.txt', 'model')
labels = classifier.predict(['sally hates computers'])
print labels

**Comment by pyk** [comment]
Hi @beaubarbour, Thanks for the report! 👍 

Hmm it seems we forgot to change the default params of `minCount` in the interface after upgrading the `fasttext(1)` library. 

Using the current version, You should be able to re-run your script with a litle modification:

```python
import fasttext
classifier = fasttext.supervised('data.train.txt', 'model', min_count=1)
labels = classifier.predict(['sally hates computers'])
print labels
```

This bug is fixed on `v0.7.2` release or #50

Please upgrade using the following command

```shell
pip install -U --no-cache-dir fasttext
``` 

After upgrading, you should be able to re-run 

```python
import fasttext
classifier = fasttext.supervised('data.train.txt', 'model')
labels = classifier.predict(['sally hates computers'])
print labels
```
smoothly.

To prevent this happen again in the future we just added [new test case](https://github.com/salestock/fastText.py/pull/50/commits/52e359c47711513f9bed8fc90eb7c4f8460f5bda) to make sure the default params is always correct
