### ISSUE TITLE
Parsing text

### ISSUE THREAD

**Issue by rahulroxx** [salestock/fastText.py#51]
Hi, I am new to machine learning . I was curious to know that if there is a solution to solve this problem with the use of fastText

string1 = "Hi i live in noida 74"
parse locations = Sector-74, Noida 

Where I have locations.txt for training set as follows 
* Sector-74, Noida
* Sector 112, Noida
..... so on 

Please help me out to this problem. 

Thanks,

**Comment by pyk** [comment]
Hi @rahulroxx,

What you are trying to achieve is called [Named-entity recognition](https://en.wikipedia.org/wiki/Named-entity_recognition) task. In this case the entity is `location`.

Yes, you can use a word vector from fastText and feed them to [LSTM-CRF model](https://github.com/monikkinom/ner-lstm) to be able to identify location from raw string. I hope this answer helps you.

I will close this issue since this is not related issue/bug for this package

**Comment by rahulroxx** [comment]
Thanks @pyk , If I need help regarding this problem where can I contact you?

**Comment by pommedeterresautee** [comment]
What you want is a crf or something which makes structured prediction. Not the purpose of fasttext.

**Comment by rahulroxx** [comment]
Thanks @pommedeterresautee for looking into this. Would you please elaborate how to solve it ?

**Comment by pommedeterresautee** [comment]
Basically, to solve NER task, you want a learner able to learn and optimize the sequence of tags and not only work on each step independently, otherwise, for instance it may tag New but not York of the expression New York (or the name and not the nickname, and so on).

There are several ways to do it, in the linear world, CRF is the most common algo family used for that.
In the Nnet world there are some architectures used, the most interesting is one applying a CRF on top of a bi-LSTM and each words being represented by both some character vectors and a word vector. If you are working on English, it s a too simple language to use the Nnet. If you are working on French/Arabic/German... the nnet option may be interesting.
